version: "3.8"

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    build:
      context: requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mariadb
    env_file:
      - .env
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    build:
      context: requirements/wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    expose:
      - "9000"

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    build:
      context: requirements/nginx
    networks:
      - inception
    ports:
      - "433:433"
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
    environment:
      - .env

# Create volumes
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/lpaulo-d/data/mariadb
      o: bind
    name: mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/lpaulo-d/data/wordpress
      o: bind
    name: wordpress

# Create a bridge network by default
networks:
  inception:
    name: inception
    driver: bridge
